"""Versioned, public system-profile seeds."""

from __future__ import annotations

from auction_watch.core.models import ContextRule, SearchProfile

CONSOLAS_SEED_KEY = "auction-watch-consolas"
CONSOLAS_SEED_VERSION = 1


def consoles_profile() -> SearchProfile:
    """Return a fresh copy of the public console-oriented system profile."""

    return SearchProfile(
        id="consolas",
        name="Auction Watch Consolas",
        kind="system",
        locked=True,
        seed_key=CONSOLAS_SEED_KEY,
        seed_version=CONSOLAS_SEED_VERSION,
        enabled=True,
        keywords_any=(
            "nintendo",
            "playstation",
            "ps1",
            "ps one",
            "psx",
            "xbox",
            "sega",
            "atari",
            "game boy",
            "game boy advance",
            "game boy advance sp",
            "game boy color",
            "game boy pocket",
            "game boy micro",
            "game & watch",
            "gba",
            "gbc",
            "gamecube",
            "n64",
            "nintendo 64",
            "super nintendo",
            "family",
            "family computer",
            "famicom",
            "famiclone",
            "family game",
            "polystation",
            "poly station",
            "dynacom",
            "terminator",
            "mega drive",
            "sega genesis",
            "sega cd",
            "mega cd",
            "32x",
            "dreamcast",
            "master system",
            "saturn",
            "game gear",
            "psp",
            "ps vita",
            "ps2",
            "ps3",
            "ps4",
            "ps5",
            "switch",
            "wii",
            "wii u",
            "3ds",
            "2ds",
            "ds",
            "ds lite",
            "dsi",
            "nes",
            "snes",
            "joystick",
            "joysticks",
            "joistick",
            "joisticks",
            "gamepad",
            "control",
            "controles",
            "dualshock",
            "dualsense",
            "joy-con",
            "wiimote",
            "mario",
            "pokemon",
            "zelda",
            "kirby",
            "sonic",
            "donkey kong",
            "metroid",
            "videojuego",
            "videojuegos",
            "cartucho",
            "cartuchos",
            "arcade",
            "pong",
            "tele-sports",
            "telesports",
            "soundic",
            "radofin",
            "neo geo",
            "pc engine",
            "turbografx",
            "colecovision",
            "intellivision",
            "odyssey",
            "vectrex",
            "nintento",
            "nitendo",
            "nintendoo",
            "playsation",
            "playstaton",
            "pley station",
            "gamevoi",
        ),
        keywords_all=(),
        exact_phrases=(),
        exclude_keywords=("impresora", "tinta", "router", "industrial"),
        boost_keywords={
            "nintendo": 12,
            "playstation": 12,
            "sega": 12,
            "atari": 12,
            "xbox": 12,
            "mario": 8,
            "pokemon": 8,
            "zelda": 8,
            "kirby": 8,
            "sonic": 8,
            "donkey kong": 8,
            "metroid": 8,
            "colección": 2,
            "original": 2,
            "completo": 2,
        },
        risk_keywords={
            "no prende": 8,
            "no funciona": 8,
            "sin probar": 8,
            "sin testear": 8,
            "para repuesto": 8,
            "repuesto": 8,
            "pantalla rota": 8,
            "roto": 8,
            "fall": 8,
            "detalle": 5,
            "sin cargador": 5,
            "sin cables": 5,
            "sin cable": 5,
            "incompleto": 8,
            "faltantes": 8,
            "no se probó": 8,
            "no probado": 8,
            "a la vista": 5,
        },
        context_rules=(
            ContextRule(
                term="control",
                required_any=(
                    "consola",
                    "videojuego",
                    "gaming",
                    "nintendo",
                    "playstation",
                    "xbox",
                    "sega",
                    "atari",
                ),
            ),
            ContextRule(
                term="controles",
                required_any=(
                    "consola",
                    "videojuego",
                    "gaming",
                    "nintendo",
                    "playstation",
                    "xbox",
                    "sega",
                    "atari",
                ),
            ),
            ContextRule(
                term="switch",
                excluded_any=(
                    "network switch",
                    "switch de red",
                    "ethernet",
                    "gigabit",
                    "router",
                    "rack",
                    "poe",
                    "rj45",
                    "switch hdmi",
                ),
            ),
            ContextRule(term="pong", excluded_any=("ping pong",)),
            ContextRule(
                term="odyssey",
                required_any=("consola", "videojuego", "gaming", "atari", "nintendo", "sega"),
            ),
            ContextRule(
                term="terminator",
                required_any=("consola", "videojuego", "gaming", "nintendo", "sega", "family game"),
            ),
            ContextRule(
                term="cartucho",
                required_any=(
                    "consola",
                    "videojuego",
                    "atari",
                    "nintendo",
                    "sega",
                    "game boy",
                    "arcade",
                ),
            ),
            ContextRule(
                term="cartuchos",
                required_any=(
                    "consola",
                    "videojuego",
                    "atari",
                    "nintendo",
                    "sega",
                    "game boy",
                    "arcade",
                ),
            ),
        ),
        source_ids=("bavastro", "castells", "remotes", "todoremates", "prado"),
        minimum_score=0,
        notification_mode="disabled",
    )


def clone_as_user(
    profile: SearchProfile, profile_id: str, name: str | None = None
) -> SearchProfile:
    """Clone a system or user profile into a completely editable user profile."""

    values = profile.model_dump()
    values.update(
        {
            "id": profile_id,
            "name": name or f"Copia de {profile.name}",
            "kind": "user",
            "locked": False,
            "seed_key": None,
            "seed_version": 0,
        }
    )
    return SearchProfile(**values)
